### ISSUE TITLE
cmake travis error

### ISSUE THREAD

**Issue by michalkielan** [michal915/MatrixLibs#20]
Error in.travis when cmake for google benchmark has been started

```
CMake 2.8.11 or higher is required. You are running version 2.8.7
```

@JaroslawWiosna

**Comment by JaroslawWiosna** [comment]
Based [on](http://askubuntu.com/questions/428772/how-to-install-specific-version-of-some-package/428778l)
After change to:

> ```
>     packages:
>         - cmake=2.8.11
> ```

E: Version '2.8.11' for 'cmake' was not found

**Comment by JaroslawWiosna** [comment]
d7f29f0439c6
 Based on
[1](http://stackoverflow.com/questions/32350262/cmake-update-version-not-found) and [2](https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon)
error is:

> Disallowing sources: smspillaz
> To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon

**Comment by JaroslawWiosna** [comment]
Those guys have the same problem:
[https://github.com/travis-ci/apt-source-whitelist/issues/93](https://github.com/travis-ci/apt-source-whitelist/issues/93)
[https://github.com/travis-ci/travis-ci/issues/5431](https://github.com/travis-ci/travis-ci/issues/5431)
However, I cannot restart build on the travis webpage...

Have a look at [https://github.com/travis-ci/apt-package-whitelist](https://github.com/travis-ci/apt-package-whitelist) <-- perhaps one can check if specific repo can be used with travis

> Update: commenters point out that "Ubuntu 12.04 is only shipping v2.8.7" and "14.04 is still shipping 2.8". That is for a reason: 12.04 and 14.04 are LTS releases of Ubuntu. LTS releases are intended to remain stable for 5 years, so they receive security and critical updates only. You will most certainly not see an upgrade of cmake happen in an LTS release. You will in non-LTS releases.

from [http://askubuntu.com/questions/355565/how-to-install-latest-cmake-version-in-linux-ubuntu-from-command-line](http://askubuntu.com/questions/355565/how-to-install-latest-cmake-version-in-linux-ubuntu-from-command-line)

**Comment by JaroslawWiosna** [comment]
I use a hint from [https://github.com/travis-ci/travis-ci/issues/4631#issuecomment-191153634](https://github.com/travis-ci/travis-ci/issues/4631#issuecomment-191153634)
Log from [MatrixLibs/builds/171604478](https://travis-ci.org/JaroslawWiosna/MatrixLibs/builds/171604478)

> make
> Scanning dependencies of target benchmark
> [  3%] Building CXX object src/CMakeFiles/benchmark.dir/complexity.cc.o
> [  7%] Building CXX object src/CMakeFiles/benchmark.dir/timers.cc.o
> [ 10%] Building CXX object src/CMakeFiles/benchmark.dir/commandlineflags.cc.o
> [ 14%] Building CXX object src/CMakeFiles/benchmark.dir/csv_reporter.cc.o
> [ 17%] Building CXX object src/CMakeFiles/benchmark.dir/sysinfo.cc.o
> [ 21%] Building CXX object src/CMakeFiles/benchmark.dir/colorprint.cc.o
> [ 25%] Building CXX object src/CMakeFiles/benchmark.dir/reporter.cc.o
> [ 28%] Building CXX object src/CMakeFiles/benchmark.dir/string_util.cc.o
> [ 32%] Building CXX object src/CMakeFiles/benchmark.dir/sleep.cc.o
> [ 35%] Building CXX object src/CMakeFiles/benchmark.dir/json_reporter.cc.o
> [ 39%] Building CXX object src/CMakeFiles/benchmark.dir/console_reporter.cc.o
> [ 42%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
> [ 46%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark.cc.o
> Linking CXX static library libbenchmark.a
> [ 46%] Built target benchmark
> Scanning dependencies of target basic_test
> [ 50%] Building CXX object test/CMakeFiles/basic_test.dir/basic_test.cc.o
> Linking CXX executable basic_test
> ../src/libbenchmark.a(timers.cc.o): In function `benchmark::ProcessCPUUsage()':
> timers.cc:(.text+0x105): undefined reference to`clock_gettime'
> ../src/libbenchmark.a(timers.cc.o): In function `benchmark::ThreadCPUUsage()':
> timers.cc:(.text+0x14f): undefined reference to`clock_gettime'
> collect2: error: ld returned 1 exit status
> make[2]: **\* [test/basic_test] Error 1
> make[1]: **\* [test/CMakeFiles/basic_test.dir/all] Error 2
> make: **\* [all] Error 2
> The command "make" failed and exited with 2 during .
> Your build has been stopped.

@michal915 It seems that this is no longer cmake error, but benchmark error. I am assigning this task to you then :D

**Comment by JaroslawWiosna** [comment]
@michal915 It would be nice if you will merge #23 (and squash 8 commits to one) to master asap
