### ISSUE TITLE
Convolution enhancement

### ISSUE THREAD

**Issue by JaroslawWiosna** [michal915/MatrixLibs#22]
> ```
>  TODO Allow kernel to be square matrix of any siza
>   TODO Implement 'full' = full convolution that returns larger than ixj
>  TODO Implement 'valid' = returns smaller than ixj
> ```

**Comment by JaroslawWiosna** [comment]
You can admire my commits here #19

**Comment by michalkielan** [comment]
What is the current status?

**Comment by JaroslawWiosna** [comment]
@michal915 still in progress.

UPDATE: almost dome, I'm going to commit tonight.
UPDATE: done. please, close the issue after merging #19 to master

**Comment by michalkielan** [comment]
Great! The release has begun very soon!

**Comment by JaroslawWiosna** [comment]
#26
