### ISSUE TITLE
Test are OK, but should be failed

### ISSUE THREAD

**Issue by JaroslawWiosna** [michal915/MatrixLibs#27]
after change to     779752b
test should fail....

> 100% tests passed, 0 tests failed out of 21
> 
> Total Test time (real) =   0.05 sec

from [https://travis-ci.org/JaroslawWiosna/MatrixLibs/builds/171665292](https://travis-ci.org/JaroslawWiosna/MatrixLibs/builds/171665292)

**Comment by michalkielan** [comment]
closed, see #28
